name: Go test workflow
on: [ push ]
jobs:

  test:
    name: TEST
    runs-on: self-hosted
    
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test report check
      run: |
        echo -e "\n PWD \n"
        pwd
        echo -e "\n Data in report.xml file \n"
        cat test1/test-reports/report.xml
    - name: Running Test
      run: go test ./... -v
      
  publish-test-report:
    if: always()
    needs: [test]
    name: Publish Test Report
    runs-on: self-hosted
    steps:
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: test1/test-reports/report.xml
