name: Go
on: [ push ]
jobs:
  test:
    name: TEST
    runs-on: self-hosted
    
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Running Test
      run: go test -v ./...
